services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.7
    # 强制设置容器内的工作目录
    working_dir: /srv/jekyll
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      # 核心修改：将容器内的路径映射到你本地的 vendor/bundle
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
      - PWD=/srv/jekyll

    command: >
      bash -c "git config --global --add safe.directory '*' && 
      bundle config set --local path 'vendor/bundle' && 
      bundle install && 
      bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload"